# =============================================================================
# VALORES DE HELM — kube-prometheus-stack
# =============================================================================

prometheus:
  service:
    type: NodePort
    nodePort: 32001
  prometheusSpec:
    scrapeInterval: 15s
    evaluationInterval: 15s

    serviceMonitorNamespaceSelector:
      matchLabels: {}

    serviceMonitorSelector:
      matchLabels: {}

    podMonitorNamespaceSelector:
      matchLabels: {}

    retention: 15d

    resources:
      requests:
        cpu: 200m
        memory: 512Mi
      limits:
        cpu: 500m
        memory: 1Gi

    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: standard
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 5Gi

grafana:
  enabled: true
  adminUser: saoriAdmin
  adminPassword: saori123

  service:
    type: NodePort
    nodePort: 32000

  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: Prometheus
          type: prometheus
          url: http://prometheus-kube-prometheus-prometheus:9090
          isDefault: false
          access: proxy

  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
        - name: "taller"
          orgId: 1
          folder: "Taller Kubernetes"
          type: file
          disableDeletion: false
          editable: true
          options:
            path: /var/lib/grafana/dashboards/taller

alertmanager:
  enabled: true
  alertmanagerSpec:
    resources:
      requests:
        cpu: 50m
        memory: 64Mi

nodeExporter:
  enabled: true

kubeStateMetrics:
  enabled: true

kubeControllerManager:
  enabled: false

kubeScheduler:
  enabled: false

kubeEtcd:
  enabled: false