{
 "title": "Cinema Monitoring",
 "panels": [
  {
   "title": "Estado Movie Catalog",
   "type": "stat",
   "gridPos": { "x": 0, "y": 0, "w": 6, "h": 4 },
   "targets": [
    { "expr": "up{job='movie-catalog'}" }
   ]
  },
  {
   "title": "Estado Ticket Sales",
   "type": "stat",
   "gridPos": { "x": 6, "y": 0, "w": 6, "h": 4 },
   "targets": [
    { "expr": "up{job='ticket-sales'}" }
   ]
  },
  {
   "title": "Tasa de Búsquedas (Req/s)",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 0, "w": 12, "h": 6 },
   "targets": [
    {
     "expr": "rate(movies_search_count_total[1m])"
    }
   ]
  },
  {
   "title": "Latencia de Reserva (ms)",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 4, "w": 12, "h": 6 },
   "targets": [
    {
     "expr": "rate(movies_reservation_time_seconds_sum[1m]) / rate(movies_reservation_time_seconds_count[1m])"
    }
   ]
  },
  {
   "title": "Asientos Disponibles (Negocio)",
   "type": "stat",
   "gridPos": { "x": 0, "y": 10, "w": 6, "h": 4 },
   "targets": [
    { "expr": "movies_seats_available" }
   ]
  },
  {
   "title": "Ventas Exitosas (Negocio)",
   "type": "timeseries",
   "gridPos": { "x": 6, "y": 10, "w": 18, "h": 6 },
   "targets": [
    { "expr": "tickets_sales_success_total" }
   ]
  }
 ]
}