server.port=8081
spring.application.name=ticket-sales
management.endpoints.web.exposure.include=health,prometheus
management.endpoint.health.probes.enabled=true
management.metrics.tags.application=${spring.application.name}

# Expose prometheus metrics at /metrics instead of /actuator/prometheus
management.endpoints.web.base-path=/
management.endpoints.web.path-mapping.prometheus=metrics

# URL of Service A. Defaults to localhost for local testing, overridden in K8s
movie.catalog.url=http://localhost:8080
